steps:
  - name: maven:3.6.0-jdk-11-slim
    entrypoint: 'mvn'
    args: ['clean', 'install', '-DskipTests']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}', '.']
  - id: 'flyway-run'
     name: '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}:latest'
     entrypoint: 'sh'
     secretEnv: ['DBT_SA']
     args: ['/FlywaySchemaBigquery/flyway.sh']

images: 
 - '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}'

substitutions:
  _IMAGE_NAME: 'flywaycchemabigquery'
  _REPOSITORY: 'docker'
  _LOCATION: 'us-central1'
  
availableSecrets:
  secretManager:
  - versionName: 'projects/$PROJECT_ID/secrets/dbt-sa/versions/1'
    env: 'DBT_SA'
