steps:
  - name: maven:3.6.0-jdk-11-slim
    entrypoint: 'mvn'
    args: ['clean', 'install', '-DskipTests']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/flywaycchemabigquery', '.']
  - id: 'flyway-run'
    name: '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}:latest'
    entrypoint: 'sh'
    secretEnv: ['DBT_SA']
    env: ['PROJECT_ID=$PROJECT_ID', 'LOCATION=$_LOCATION', 'BUCKET_NAME=$PROJECT_ID-dbt']
    args: ['./flyway.sh']
images: ['gcr.io/$PROJECT_ID/flywaycchemabigquery']

substitutions:
  _IMAGE_NAME: 'flywaycchemabigquery'
  _REPOSITORY: 'docker'
  _LOCATION: 'us-central1'

availableSecrets:
  secretManager:
  - versionName: 'projects/$PROJECT_ID/secrets/dbt-sa/versions/1'
    env: 'DBT_SA'
