steps:
  - name: maven:3.6.0-jdk-11-slim
    entrypoint: 'mvn'
    args: ['clean', 'install', '-DskipTests']
  - name: 'gcr.io/cloud-builders/docker'
    secretEnv: ['DBT_SA']
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/flywaycchemabigquery', '.']
images: ['gcr.io/$PROJECT_ID/flywaycchemabigquery']
availableSecrets:
  secretManager:
  - versionName: 'projects/$PROJECT_ID/secrets/dbt-sa/versions/1'
    env: 'DBT_SA'
