steps:
  - id: 'flyway-run'
    name: '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}:latest'
    entrypoint: 'sh'
    secretEnv: ['FLYWAY_SA']
    env: ['PROJECT_ID=$PROJECT_ID', 'LOCATION=$_LOCATION', 'BUCKET_NAME=$PROJECT_ID-flyway']
    args: ['/FlywaySchemaBigquery/flyway.sh']

substitutions:
  _IMAGE_NAME: 'flywayschema'
  _REPOSITORY: 'docker'
  _LOCATION: 'us-central1'

availableSecrets:
  secretManager:
    - versionName: 'projects/$PROJECT_ID/secrets/dbt-sa/versions/1'
      env: 'FLYWAY_SA'
